# -*- coding: utf-8 -*-

# Dialog implementation generated from reading ui file 'createplaylist.ui'
#
# Note that this does not match the corresponding ui file due to manual changes after converting to a py file
#
# This creates a screen for creating playlists



from PyQt5 import QtCore, QtGui, QtWidgets
import main


class Ui_Dialog(object):
    def setupUi(self, Dialog, MainWindow):
        Dialog.setObjectName("Dialog")
        Dialog.resize(625, 477)
        Dialog.setStyleSheet("background-color:qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0, stop:0 rgba(91, 0, 190, 255), stop:1 rgba(130, 119, 255, 255))")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Search = QtWidgets.QHBoxLayout()
        self.Search.setObjectName("Search")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.Search.addItem(spacerItem)
        self.SearchBar = QtWidgets.QLineEdit(Dialog)
        self.SearchBar.setStyleSheet("background-color: rgba(255, 255, 255, 255);")
        self.SearchBar.setObjectName("SearchBar")
        self.Search.addWidget(self.SearchBar)
        self.searchButton = QtWidgets.QPushButton(Dialog)
        self.searchButton.setStyleSheet("background-color: rgba(255, 255, 255, 255);")
        self.searchButton.setObjectName("searchButton")
        self.Search.addWidget(self.searchButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.Search.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.Search)
        self.SearchList = QtWidgets.QHBoxLayout()
        self.SearchList.setObjectName("SearchList")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.SearchList.addItem(spacerItem2)
        self.searchedSongsList = QtWidgets.QListWidget(Dialog)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.searchedSongsList.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.searchedSongsList.setFont(font)
        self.searchedSongsList.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.searchedSongsList.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.searchedSongsList.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.searchedSongsList.setObjectName("searchedSongsList")
        self.SearchList.addWidget(self.searchedSongsList)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.SearchList.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.SearchList)
        self.Buttons = QtWidgets.QHBoxLayout()
        self.Buttons.setObjectName("Buttons")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.Buttons.addItem(spacerItem4)
        self.playlistFromSongButton = QtWidgets.QPushButton(Dialog)
        self.playlistFromSongButton.setStyleSheet("background-color: rgba(255, 255, 255, 255);")
        self.playlistFromSongButton.setObjectName("playlistFromSongButton")
        self.Buttons.addWidget(self.playlistFromSongButton)
        self.cancelButton = QtWidgets.QPushButton(Dialog)
        self.cancelButton.setStyleSheet("background-color: rgba(255, 255, 255, 255);")
        self.cancelButton.setObjectName("cancelButton")
        self.Buttons.addWidget(self.cancelButton)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.Buttons.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.Buttons)

        self.retranslateUi(Dialog)
        self.searchButton.clicked.connect(lambda: main.search(self))
        self.playlistFromSongButton.clicked.connect(lambda: main.create_playlist(self, Dialog, MainWindow))
        self.cancelButton.clicked.connect(lambda: main.cancel(self, Dialog))
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Create Playlist"))
        self.searchButton.setText(_translate("Dialog", "Search"))
        self.playlistFromSongButton.setText(_translate("Dialog", "Create Playlist From Selected Song"))
        self.cancelButton.setText(_translate("Dialog", "Cancel"))
